---------------------------------------------------------------------------------------------------------------------------
-- ESTABLISHMENT DIMENSION
-- Grain: 1 row = 1 unique establishment (identified by CAMIS code)
---------------------------------------------------------------------------------------------------------------------------

DROP TABLE IF EXISTS establishment_dim CASCADE;

CREATE TABLE establishment_dim (
    establishment_key SERIAL PRIMARY KEY,      -- Surrogate key generated by the database
    camis_code VARCHAR(10) NOT NULL UNIQUE,    -- Natural key identifying the establishment
    establishment_name VARCHAR(255),           -- Commercial name of the establishment
    cuisine_description VARCHAR(100)           -- Cuisine type associated with the establishment
);

---------------------------------------------------------------------------------------------------------------------------
-- POPULATE ESTABLISHMENT DIMENSION
---------------------------------------------------------------------------------------------------------------------------

INSERT INTO establishment_dim (
    camis_code,
    establishment_name,
    cuisine_description
)
SELECT DISTINCT
    -- CAMIS code uniquely identifies an establishment across all inspections
    camis_code,
    establishment_name,
    cuisine_description
FROM clean_data_table
WHERE camis_code IS NOT NULL;

---------------------------------------------------------------------------------------------------------------------------
-- VALIDATION CHECKS
---------------------------------------------------------------------------------------------------------------------------

-- Total number of distinct establishments
SELECT COUNT(*) AS total_establishments
FROM establishment_dim;
-- 30659

-- Visual sample
SELECT *
FROM establishment_dim
ORDER BY establishment_key
LIMIT 20;
